name: Setup releases
on: workflow_dispatch
jobs:
  set-vars:
    name: Get version, release, and notes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-ver.outputs.version }}
      release: ${{ steps.set-rel.outputs.release }}
    steps:
      - name: Set Version
        id: set-ver
        run: |
          echo "version=$(gh release list --limit 1 -R rockstor/rockstor-core | cut -f1 | cut -d "-" -f1)" >> "$GITHUB_OUTPUT"
      - name: Set Release
        id: set-rel
        run: |
          echo "release=$(gh release list --limit 1 -R rockstor/rockstor-core | cut -f1 | cut -d "-" -f2)" >> "$GITHUB_OUTPUT"
  print-vars:
    name: Print version and release
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - env:
          VERSION: ${{ needs.set-vars.outputs.version }}
          RELEASE: ${{ needs.set-vars.outputs.release }}
        run: echo "Rockstor version-release detected is $VERSION-$RELEASE"
#    update_rocsktor-jslibs:
#      name: Update the rockstor-jslibs repo
#    update_rockstor-rpmbuild:
#      name: Update the rocsktor-rpmbuild repo