name: Trigger releases
on: workflow_dispatch
jobs:
  set-vars:
    name: Get version, release, and notes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-ver.outputs.version }}
      release: ${{ steps.set-rel.outputs.release }}
#      relnotes: ${{ steps.set-relnotes.outputs.relnotes }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set Version
        id: set-ver
        run: |
          echo "version=$(gh release list --limit 1 -R rockstor/rockstor-core | cut -f1 | cut -d "-" -f1)" >> "$GITHUB_OUTPUT"
      - name: Set Release
        id: set-rel
        run: |
          echo "release=$(gh release list --limit 1 -R rockstor/rockstor-core | cut -f1 | cut -d "-" -f2)" >> "$GITHUB_OUTPUT"
#      - name: Set Release Notes
#        id: set-relnotes
#        run: |
#          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
#          echo "relnotes<<$EOF" >> "$GITHUB_OUTPUT"
#          gh release view ${{ steps.set-ver.outputs.version }}-${{ steps.set-rel.outputs.release }} \
#          -R rockstor/rockstor-core --json body --template '{{ .body }}{{"\n"}}' | \
#          grep '^\* ' | \
#          sed 's|in https://github.com/rockstor/rockstor-core/pull/[0-9]*||g' | \
#          sed 's|by @|@|g' | \
#          sed 's|* |-|g' | \
#          tac >> "$GITHUB_OUTPUT"
#          echo "$EOF" >> "$GITHUB_OUTPUT"

  trigger_rockstor-jslibs_release:
    name: Trigger a release in the rockstor-jslibs repo
    runs-on: ubuntu-latest
    needs: set-vars
    permissions: write-all
    env:
      VERSION: ${{ needs.set-vars.outputs.version }}
      GH_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: trigger the rockstor-jslibs workflow
        id: trigger-jslibs-workflow
        run: |
          gh workflow run update_release.yml \
          -f version=$VERSION \
          -R FroggyFlox/testrepo-dep1

  trigger_rockstor-rpmbuild-updates:
    name: Trigger the update of the rockstor-rpmbuild repo
    runs-on: ubuntu-latest
    needs: set-vars
    permissions: write-all
    env:
      VERSION: ${{ needs.set-vars.outputs.version }}
      RELEASE: ${{ needs.set-vars.outputs.release }}
#      RELNOTES: ${{ needs.set-vars.outputs.relnotes }}
      GH_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: trigger the rockstor-jslibs workflow
        id: trigger-jslibs-workflow
        run: |
          gh workflow run update_spec_file.yml \
          -f version=$VERSION \
          -f release=$RELEASE \
          -R FroggyFlox/testrepo-dep2
